[patch.crates-io.visualization_msgs]
path = "/opt/ros/rust_ros2_env/install/visualization_msgs/share/visualization_msgs/rust"

[patch.crates-io.test_msgs]
path = "/opt/ros/rust_ros2_env/install/test_msgs/share/test_msgs/rust"

[patch.crates-io.examples_rclrs_minimal_client_service]
path = "/opt/ros/rust_ros2_env/install/examples_rclrs_minimal_client_service/share/examples_rclrs_minimal_client_service/rust"

[patch.crates-io.example_interfaces]
path = "/opt/ros/rust_ros2_env/install/example_interfaces/share/example_interfaces/rust"

[patch.crates-io.action_msgs]
path = "/opt/ros/rust_ros2_env/install/action_msgs/share/action_msgs/rust"

[patch.crates-io.unique_identifier_msgs]
path = "/opt/ros/rust_ros2_env/install/unique_identifier_msgs/share/unique_identifier_msgs/rust"

[patch.crates-io.trajectory_msgs]
path = "/opt/ros/rust_ros2_env/install/trajectory_msgs/share/trajectory_msgs/rust"

[patch.crates-io.stereo_msgs]
path = "/opt/ros/rust_ros2_env/install/stereo_msgs/share/stereo_msgs/rust"

[patch.crates-io.std_srvs]
path = "/opt/ros/rust_ros2_env/install/std_srvs/share/std_srvs/rust"

[patch.crates-io.shape_msgs]
path = "/opt/ros/rust_ros2_env/install/shape_msgs/share/shape_msgs/rust"

[patch.crates-io.sensor_msgs]
path = "/opt/ros/rust_ros2_env/install/sensor_msgs/share/sensor_msgs/rust"

[patch.crates-io.rust_pubsub]
path = "/opt/ros/rust_ros2_env/install/rust_pubsub/share/rust_pubsub/rust"

[patch.crates-io.nav_msgs]
path = "/opt/ros/rust_ros2_env/install/nav_msgs/share/nav_msgs/rust"

[patch.crates-io.diagnostic_msgs]
path = "/opt/ros/rust_ros2_env/install/diagnostic_msgs/share/diagnostic_msgs/rust"

[patch.crates-io.geometry_msgs]
path = "/opt/ros/rust_ros2_env/install/geometry_msgs/share/geometry_msgs/rust"

[patch.crates-io.examples_rclrs_minimal_pub_sub]
path = "/opt/ros/rust_ros2_env/install/examples_rclrs_minimal_pub_sub/share/examples_rclrs_minimal_pub_sub/rust"

[patch.crates-io.actionlib_msgs]
path = "/opt/ros/rust_ros2_env/install/actionlib_msgs/share/actionlib_msgs/rust"

[patch.crates-io.ackermann_msgs]
path = "/opt/ros/rust_ros2_env/install/ackermann_msgs/share/ackermann_msgs/rust"

[patch.crates-io.std_msgs]
path = "/opt/ros/rust_ros2_env/install/std_msgs/share/std_msgs/rust"

[patch.crates-io.statistics_msgs]
path = "/opt/ros/rust_ros2_env/install/statistics_msgs/share/statistics_msgs/rust"

[patch.crates-io.examples_rclrs_message_demo]
path = "/opt/ros/rust_ros2_env/install/examples_rclrs_message_demo/share/examples_rclrs_message_demo/rust"

[patch.crates-io.rclrs]
path = "/opt/ros/rust_ros2_env/install/rclrs/share/rclrs/rust"

[patch.crates-io.rosgraph_msgs]
path = "/opt/ros/rust_ros2_env/install/rosgraph_msgs/share/rosgraph_msgs/rust"

[patch.crates-io.rclrs_example_msgs]
path = "/opt/ros/rust_ros2_env/install/rclrs_example_msgs/share/rclrs_example_msgs/rust"

[patch.crates-io.composition_interfaces]
path = "/opt/ros/rust_ros2_env/install/composition_interfaces/share/composition_interfaces/rust"

[patch.crates-io.rcl_interfaces]
path = "/opt/ros/rust_ros2_env/install/rcl_interfaces/share/rcl_interfaces/rust"

[patch.crates-io.lifecycle_msgs]
path = "/opt/ros/rust_ros2_env/install/lifecycle_msgs/share/lifecycle_msgs/rust"

[patch.crates-io.builtin_interfaces]
path = "/opt/ros/rust_ros2_env/install/builtin_interfaces/share/builtin_interfaces/rust"

[patch.crates-io.rosidl_runtime_rs]
path = "/opt/ros/rust_ros2_env/install/rosidl_runtime_rs/share/rosidl_runtime_rs/rust"

[patch.crates-io.rust_ws]
path = "/ros2_ws/Rust_F1Tenth_ws/sim_ws_rust/install/rust_ws/share/rust_ws/rust"
